app: act-jepa crane_x7

# --------------------- Training ---------------------
training_arguments:
  # seed
  seed: 42
  max_steps: 5000

  # optimization
  optim: adamw_torch
  lr_scheduler_type: cosine
  warmup_ratio: 0.04
  learning_rate: 6.0e-4
  weight_decay: 0.1

  # dataloader
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  dataloader_num_workers: 16
  dataloader_drop_last: true

  # log training
  logging_strategy: steps
  logging_steps: 50
  logging_first_step: true
  log_on_each_node: false

  # eval_strategy: steps
  # eval_steps: 0.25
  # eval_delay: 1 # skip eval at the beginning

  save_strategy: steps
  save_steps: 1000 # save every n steps (and the last step)

  # other
  gradient_accumulation_steps: 1
  full_determinism: true
  report_to: ['wandb']

normalize_keys: ['action', 'observation.state']

callbacks: ['EmaUpdateCallback', 'AgentEvaluatorCallback', 'LogAuxiliaryLossCallback']

# --------------------- Features ---------------------
feature_config: &horizon
  observation.image: 1
  observation.state: 30
  episode_index: 1
  task_index: 1
  action: 30


# --------------------- Policy model ---------------------
model:
  policy_name: ActionChunkingPolicy
  class_name: ActJepaModel
  target_update: ema
  horizon: *horizon

  encoder: &common_params
    hidden_size: 512
    intermediate_size: 2048
    num_hidden_layers: 4
    num_attention_heads: 8
    hidden_act: relu
    attention_dropout: 0.1
    horizon: *horizon

  target_encoder:
    <<: *common_params
    causal: false

  decoder:
    <<: *common_params
    num_hidden_layers: 1
    causal: false

  predictor:
    <<: *common_params
    # narrow predictor
    hidden_size: 128
    intermediate_size: 512
    causal: false

  sigreg:
    weight: 0.0
    knots: 17
    num_proj: 1024

  loss_weights:
    action: 1.0
    jepa: 1.0
    abstract: 1.0
    target_sigreg: 0.0
    context_sigreg: 0.0

ema_start: 0.996
ema_end: 1.0

# --------------------- CRANE-X7 settings ---------------------
dataset:
  repo_ids:
    - local/crane_x7_lift
  revision: 'main'
  use_videos: True
  train_episodes_range: [0, 50]
  test_episodes_range: [50, 60]

env:
  rollout_steps: 1000
  rollout_delay: 1 # skip rollout at the beginning

  num_episodes: 20
  seed: 1000

  env_kwargs:
    id: CraneX7-v0
    img_size: 128
    max_episode_steps: 300

  env_names:
    - lift-cube

  eval_camera_views:
    - right
    - left
    - front

state_predictor: !inc state_predictor.yaml
state_predictor_every_n_steps: 1000
