app: state predictor crane_x7


# --------------------- Training ---------------------
training_arguments:
  # seed
  seed: 42
  max_steps: 250

  # optimization
  optim: adamw_torch
  lr_scheduler_type: cosine
  warmup_ratio: 0.08
  learning_rate: 6.0e-4
  weight_decay: 0.1

  # dataloader
  per_device_train_batch_size: 512
  per_device_eval_batch_size: 512
  dataloader_num_workers: 16
  dataloader_persistent_workers: true
  dataloader_drop_last: true

  # log training
  logging_strategy: steps
  logging_steps: 250
  logging_first_step: true
  log_on_each_node: false

  # eval_strategy: steps
  # eval_steps: 0.25
  # eval_delay: 1 # skip eval at the beginning

  save_strategy: steps
  save_steps: 500 # save every n steps (and the last step)

  # other
  gradient_accumulation_steps: 1
  full_determinism: true
  report_to: ['wandb']

normalize_keys: ['action', 'observation.state']

callbacks: ['LogAuxiliaryLossCallback']

# --------------------- Features ---------------------
feature_config: &horizon
  observation.image: 1
  observation.state: 30
  episode_index: 1
  task_index: 1
  action: 30


# --------------------- Model ---------------------
model:
  class_name: StatePredictorModel
  horizon: *horizon

  predictor:
    hidden_size: 512
    intermediate_size: 2048
    num_hidden_layers: 4
    num_attention_heads: 8
    hidden_act: relu
    attention_dropout: 0.1
    horizon: *horizon
    causal: true


# --------------------- CRANE-X7 settings ---------------------
dataset:
  repo_ids:
    - local/crane_x7_lift
  revision: 'main'
  use_videos: True
  train_episodes_range: [0, 100]
  test_episodes_range: [100, 120]
