app: act-lejepa mani_skill

# --------------------- Training ---------------------
training_arguments:
  # seed
  seed: 42
  max_steps: 5000

  # optimization
  optim: adamw_torch
  lr_scheduler_type: cosine
  warmup_ratio: 0.04
  learning_rate: 6.0e-4
  weight_decay: 0.1

  # dataloader
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  dataloader_num_workers: 16
  dataloader_drop_last: true

  # log training
  logging_strategy: steps
  logging_steps: 50
  logging_first_step: true
  log_on_each_node: false
  
  save_strategy: steps
  save_steps: 2000 # save every n steps (and the last step)

  # other
  gradient_accumulation_steps: 1
  full_determinism: true
  report_to: ['wandb']

normalize_keys: []

callbacks: ['LogAuxiliaryLossCallback', 'AgentEvaluatorCallback']

# --------------------- Features ---------------------
feature_config: &horizon
  observation.image: 1
  observation.state: 30
  episode_index: 1
  task_index: 1
  action: 30


# --------------------- Policy model ---------------------
model:
  policy_name: ActionChunkingPolicy
  class_name: ActLejepaModel
  target_update: grad
  horizon: *horizon

  encoder: &common_params
    hidden_size: 512
    intermediate_size: 2048
    num_hidden_layers: 4
    num_attention_heads: 8
    hidden_act: relu
    attention_dropout: 0.1
    horizon: *horizon
  
  target_encoder:
    <<: *common_params
    causal: false
    attention_dropout: 0.0 # clean labels: no dropout in the target path

  decoder:
    <<: *common_params
    num_hidden_layers: 1
    causal: false

  predictor:
    <<: *common_params
    # narrow predictor
    hidden_size: 128 
    intermediate_size: 512
    causal: false

  sigreg:
    weight: 0.09
    knots: 17
    num_proj: 1024

  loss_weights:
    action: 1.0
    jepa: 1.0
    abstract: 1.0
    target_sigreg: 0.09
    context_sigreg: 0.0

# --------------------- ManiSkill settings ---------------------
dataset:
  repo_ids:
    - alek98/ManiSkill_PickCube-v1
    - alek98/ManiSkill_PushCube-v1
    - alek98/ManiSkill_StackCube-v1
    - alek98/ManiSkill_PullCubeTool-v1
    - alek98/ManiSkill_PegInsertionSide-v1

  revision: 'main'
  use_videos: True
  train_episodes_range: [0, 40]
  test_episodes_range: [40, 50]

env:
  rollout_steps: 1000
  rollout_delay: 1 # skip rollout at the beginning

  num_episodes: 10
  seed: 1000
  
  env_kwargs:
    id: ManiSkill-v3
    img_size: 128
    max_episode_steps: 300 # max num steps
    control_mode: pd_joint_pos # note that these are absolute positions

  env_names:
    - PickCube-v1
    - PushCube-v1
    - StackCube-v1
    - PullCubeTool-v1
    - PegInsertionSide-v1

state_predictor: !inc state_predictor.yaml
state_predictor_every_n_steps: 1000
